name: hawkes-first-passage
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - numba>=0.57.0
  - scikit-learn>=1.3.0
  - statsmodels>=0.14.0
  - pyyaml>=6.0
  - h5py>=3.9.0
  - pytest>=7.4.0
  - black>=23.7.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  - pip
  - pip:
    - plotly>=5.15.0
    - pytest-cov>=4.1.0