"""Numerical robustness diagnostics for the Kou killed-resolvent solver.

The helpers in this module are deliberately read-only with respect to the
model: they evaluate Talbot-order convergence, characteristic-root quality,
and barrier-system conditioning without changing root selection or inversion
behaviour.
"""

from __future__ import annotations

import csv
import math
import time
from dataclasses import asdict, dataclass
from itertools import combinations
from pathlib import Path
from statistics import NormalDist
from typing import Iterable, Sequence

import numpy as np

from optimal_long_short.inversion import TalbotInverter
from optimal_long_short.kou_model import KouZTiltedDynamics
from optimal_long_short.laplace_resolvent import HomogeneousSolution, ParticularSolution
from optimal_long_short.model_params import KouParams
from optimal_long_short.monte_carlo import MonteCarlo
from optimal_long_short.moments import ConditionalMoments
from optimal_long_short.root_finder import CharacteristicRootFinder
from optimal_long_short.strategy import UnitExposureLongShortStrategy


@dataclass(frozen=True)
class TalbotConvergenceDiagnostic:
    """One value in a Talbot-order convergence study."""

    h0: float
    T: float
    M: int
    quantity: str
    k: int
    value: float
    previous_value: float | None
    absolute_change: float | None
    relative_change: float | None


@dataclass(frozen=True)
class RootQualityDiagnostic:
    """Worst-case root and barrier-system metrics over Talbot nodes."""

    h0: float
    T: float
    M: int
    k: int
    n_nodes: int
    max_relative_root_residual: float
    min_root_separation: float
    min_root_pole_distance: float
    max_barrier_condition_number: float
    max_barrier_system_residual: float


@dataclass(frozen=True)
class BarrierCancellationResiduals:
    """Residuals of the corrected killed-barrier cancellation conditions.

    ``value_at_barrier`` is the absorbing Dirichlet residual.  The other two
    fields are the coefficients of the exponential truncation corrections
    generated by the two downward jump phases.  They are not values of the
    killed jump integrals at the barrier.
    """

    value_at_barrier: complex
    downward_correction_1: complex
    downward_correction_2: complex

    @property
    def max_abs(self) -> float:
        """Maximum absolute residual across the three conditions."""
        return float(
            max(
                abs(self.value_at_barrier),
                abs(self.downward_correction_1),
                abs(self.downward_correction_2),
            )
        )


@dataclass(frozen=True)
class MonteCarloMonitoringDiagnostic:
    """One discretely monitored Monte Carlo barrier estimate."""

    h0: float
    T: float
    n_paths: int
    n_intervals: int
    interval_dt_years: float
    seed: int
    p_surv: float
    binomial_standard_error: float
    confidence_level: float
    ci_lower: float
    ci_upper: float
    laplace_M: int
    laplace_p_surv: float
    difference_from_laplace: float
    runtime_seconds: float


def talbot_nodes(M: int, T: float) -> tuple[complex, ...]:
    """Return the upper-half fixed-Talbot nodes used by ``TalbotInverter``."""
    if M < 2:
        raise ValueError(f"M must be at least 2, got {M}")
    if T <= 0.0:
        raise ValueError(f"T must be positive, got {T}")

    delta = 2.0 * M / (5.0 * T)
    nodes: list[complex] = [complex(delta)]
    for index in range(1, M):
        theta = index * np.pi / M
        cot_theta = np.cos(theta) / np.sin(theta)
        nodes.append(complex(delta * theta * (cot_theta + 1j)))
    return tuple(nodes)


def talbot_convergence_diagnostics(
    params: KouParams,
    strategy: UnitExposureLongShortStrategy,
    M_values: Iterable[int] = (12, 16, 24, 32, 40),
    moment_orders: Iterable[int] = (1, 2, 3, 4),
) -> list[TalbotConvergenceDiagnostic]:
    """Evaluate survival and killed payoff moments across Talbot orders.

    Changes are measured against the immediately preceding (smaller) Talbot
    order.  ``relative_change`` uses the larger of the two value magnitudes as
    its scale, which remains well defined when a diagnostic is near zero.
    """
    orders = tuple(sorted(set(int(k) for k in moment_orders)))
    if not orders or orders[0] < 1:
        raise ValueError("moment_orders must contain positive integers")

    quadrature_orders = tuple(sorted(set(int(M) for M in M_values)))
    if not quadrature_orders or quadrature_orders[0] < 2:
        raise ValueError("M_values must contain integers of at least 2")

    previous: dict[tuple[str, int], float] = {}
    diagnostics: list[TalbotConvergenceDiagnostic] = []
    for M in quadrature_orders:
        moments = ConditionalMoments(
            params=params,
            strategy=strategy,
            inverter=TalbotInverter(M=M),
        )
        values = [("p_surv", 0, float(moments.p_surv()))]
        values.extend(
            ("killed_moment", k, float(moments.killed_moment(k))) for k in orders
        )

        for quantity, k, value in values:
            key = (quantity, k)
            prior = previous.get(key)
            if prior is None:
                absolute_change = None
                relative_change = None
            else:
                absolute_change = abs(value - prior)
                scale = max(abs(value), abs(prior), np.finfo(float).tiny)
                relative_change = absolute_change / scale
            diagnostics.append(
                TalbotConvergenceDiagnostic(
                    h0=float(strategy.h0),
                    T=float(strategy.T),
                    M=M,
                    quantity=quantity,
                    k=k,
                    value=value,
                    previous_value=prior,
                    absolute_change=absolute_change,
                    relative_change=relative_change,
                )
            )
            previous[key] = value
    return diagnostics


def _barrier_matrix(
    dynamics: KouZTiltedDynamics,
    negative_roots: Sequence[complex],
) -> np.ndarray:
    """Build the generic three-phase barrier matrix used by the solver."""
    if len(negative_roots) != 3:
        raise ValueError(
            "Numerical diagnostics currently require the generic three-root "
            f"regime, got {len(negative_roots)} roots"
        )
    matrix = np.empty((3, 3), dtype=complex)
    for column, gamma in enumerate(negative_roots):
        matrix[0, column] = 1.0
        matrix[1, column] = dynamics.r1_neg / (dynamics.r1_neg + gamma)
        matrix[2, column] = dynamics.r2_neg / (dynamics.r2_neg + gamma)
    return matrix


def killed_barrier_cancellation_residuals(
    particular: ParticularSolution,
    q: complex,
) -> BarrierCancellationResiduals:
    """Evaluate the three corrected barrier residuals for a killed moment.

    This function is limited to the generic distinct-downward-rate regime,
    which is the regime used by the baseline calibration and the paper's
    fixed ``3 x 3`` representation.
    """
    dynamics = particular.dynamics
    if math.isclose(
        dynamics.r1_neg,
        dynamics.r2_neg,
        rel_tol=0.0,
        abs_tol=1e-8,
    ):
        raise ValueError(
            "Barrier cancellation diagnostics require distinct downward rates"
        )

    homogeneous = HomogeneousSolution(particular=particular)
    negative_roots = homogeneous._genuine_negative_roots(q)
    coefficients = homogeneous.coefficients(q)

    value_at_barrier = particular.evaluate_at_barrier(q) + coefficients.sum()

    def correction_coefficient(rate: float) -> complex:
        particular_term = particular.phase_op_neg_at_barrier(q, rate)
        homogeneous_term = sum(
            coefficient * rate / (rate + gamma)
            for coefficient, gamma in zip(coefficients, negative_roots)
        )
        return particular_term + homogeneous_term

    return BarrierCancellationResiduals(
        value_at_barrier=complex(value_at_barrier),
        downward_correction_1=complex(correction_coefficient(dynamics.r1_neg)),
        downward_correction_2=complex(correction_coefficient(dynamics.r2_neg)),
    )


def root_quality_diagnostics(
    params: KouParams,
    strategy: UnitExposureLongShortStrategy,
    M: int = 32,
    tilt_orders: Iterable[int] = (0, 1, 2, 3, 4),
) -> list[RootQualityDiagnostic]:
    """Measure root residuals, separation, pole distance, and conditioning."""
    nodes = talbot_nodes(M, strategy.T)
    diagnostics: list[RootQualityDiagnostic] = []

    for k in sorted(set(int(order) for order in tilt_orders)):
        if k < 0:
            raise ValueError("tilt_orders must be non-negative integers")
        dynamics = KouZTiltedDynamics(params=params, k=k)
        particular = (
            ParticularSolution(dynamics=dynamics, strategy=strategy) if k > 0 else None
        )

        max_root_residual = 0.0
        min_root_separation = math.inf
        min_pole_distance = math.inf
        max_condition_number = 0.0
        max_system_residual = 0.0

        poles = (
            complex(dynamics.r1_pos),
            complex(-dynamics.r1_neg),
            complex(dynamics.r2_pos),
            complex(-dynamics.r2_neg),
        )

        for q in nodes:
            roots = CharacteristicRootFinder(dynamics).find(q)
            all_roots = tuple(roots.positive) + tuple(roots.negative)
            max_root_residual = max(
                max_root_residual,
                max(abs(dynamics(root) - q) / max(1.0, abs(q)) for root in all_roots),
            )
            min_root_separation = min(
                min_root_separation,
                min(abs(left - right) for left, right in combinations(all_roots, 2)),
            )
            min_pole_distance = min(
                min_pole_distance,
                min(abs(root - pole) for root in all_roots for pole in poles),
            )

            matrix = _barrier_matrix(dynamics, roots.negative)
            condition_number = float(np.linalg.cond(matrix))
            max_condition_number = max(max_condition_number, condition_number)

            if particular is None:
                forcing = np.full(3, 1.0 / q, dtype=complex)
            else:
                forcing = np.asarray(particular.forcing_vector(q), dtype=complex)
            coefficients = np.linalg.solve(matrix, -forcing)
            system_residual = float(np.max(np.abs(matrix @ coefficients + forcing)))
            max_system_residual = max(max_system_residual, system_residual)

        diagnostics.append(
            RootQualityDiagnostic(
                h0=float(strategy.h0),
                T=float(strategy.T),
                M=M,
                k=k,
                n_nodes=len(nodes),
                max_relative_root_residual=float(max_root_residual),
                min_root_separation=float(min_root_separation),
                min_root_pole_distance=float(min_pole_distance),
                max_barrier_condition_number=float(max_condition_number),
                max_barrier_system_residual=float(max_system_residual),
            )
        )
    return diagnostics


def monte_carlo_monitoring_diagnostics(
    params: KouParams,
    strategy: UnitExposureLongShortStrategy,
    interval_counts: Iterable[int] = (63, 252, 1008),
    *,
    n_paths: int = 25_000,
    seed: int = 42,
    confidence_level: float = 0.95,
    laplace_M: int = 32,
) -> list[MonteCarloMonitoringDiagnostic]:
    """Estimate monitoring bias across grids of intervals over ``[0, T]``.

    The Monte Carlo implementation checks the barrier only at the end of each
    interval.  These results are therefore explicitly *discretely monitored*
    and are not continuous-time Monte Carlo estimates.  Confidence intervals
    use the normal approximation to the binomial survival indicator and only
    quantify path sampling error, not monitoring bias.
    """
    counts = tuple(sorted(set(int(count) for count in interval_counts)))
    if not counts or counts[0] < 1:
        raise ValueError("interval_counts must contain positive integers")
    if n_paths < 1:
        raise ValueError("n_paths must be positive")
    if not 0.0 < confidence_level < 1.0:
        raise ValueError("confidence_level must be in (0, 1)")
    if laplace_M < 2:
        raise ValueError("laplace_M must be at least 2")

    laplace_p_surv = float(
        ConditionalMoments(
            params=params,
            strategy=strategy,
            inverter=TalbotInverter(M=laplace_M),
        ).p_surv()
    )
    z_score = NormalDist().inv_cdf(0.5 + confidence_level / 2.0)

    diagnostics: list[MonteCarloMonitoringDiagnostic] = []
    for n_intervals in counts:
        simulator = MonteCarlo(
            params=params,
            strategy=strategy,
            n_paths=n_paths,
            n_steps=n_intervals,
            seed=seed,
        )
        start = time.perf_counter()
        result = simulator.run()
        runtime_seconds = time.perf_counter() - start

        p_surv = float(result.p_surv)
        standard_error = math.sqrt(p_surv * (1.0 - p_surv) / n_paths)
        half_width = z_score * standard_error
        diagnostics.append(
            MonteCarloMonitoringDiagnostic(
                h0=float(strategy.h0),
                T=float(strategy.T),
                n_paths=n_paths,
                n_intervals=n_intervals,
                interval_dt_years=float(strategy.T / n_intervals),
                seed=seed,
                p_surv=p_surv,
                binomial_standard_error=standard_error,
                confidence_level=confidence_level,
                ci_lower=max(0.0, p_surv - half_width),
                ci_upper=min(1.0, p_surv + half_width),
                laplace_M=laplace_M,
                laplace_p_surv=laplace_p_surv,
                difference_from_laplace=p_surv - laplace_p_surv,
                runtime_seconds=runtime_seconds,
            )
        )
    return diagnostics


_CSV_FIELDS = (
    "diagnostic",
    "h0",
    "T",
    "M",
    "quantity",
    "k",
    "value",
    "previous_value",
    "absolute_change",
    "relative_change",
    "n_nodes",
    "max_relative_root_residual",
    "min_root_separation",
    "min_root_pole_distance",
    "max_barrier_condition_number",
    "max_barrier_system_residual",
    "n_paths",
    "n_intervals",
    "interval_dt_years",
    "seed",
    "p_surv",
    "binomial_standard_error",
    "confidence_level",
    "ci_lower",
    "ci_upper",
    "laplace_M",
    "laplace_p_surv",
    "difference_from_laplace",
    "runtime_seconds",
)


def write_numerical_diagnostics_csv(
    path: Path,
    convergence: Iterable[TalbotConvergenceDiagnostic],
    roots: Iterable[RootQualityDiagnostic],
    monte_carlo: Iterable[MonteCarloMonitoringDiagnostic] = (),
) -> None:
    """Write convergence and root-quality diagnostics to one compact CSV."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, object]] = []
    for row in convergence:
        record = asdict(row)
        record["diagnostic"] = "talbot_convergence"
        records.append(record)
    for row in roots:
        record = asdict(row)
        record["diagnostic"] = "root_quality"
        records.append(record)
    for row in monte_carlo:
        record = asdict(row)
        record["diagnostic"] = "mc_monitoring_convergence"
        record["quantity"] = "p_surv_discretely_monitored"
        records.append(record)

    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=_CSV_FIELDS,
            extrasaction="ignore",
            lineterminator="\n",
        )
        writer.writeheader()
        for record in records:
            writer.writerow({field: record.get(field, "") for field in _CSV_FIELDS})
